---
title: "Benchmarks"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Benchmarks}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 6,
  fig.height = 4
)
```

```{r setup}
library(yyjsonr)
library(bench)
library(ggplot2)
library(tidyr)
library(ggbeeswarm)
library(geojsonsf)
library(sf)
```


Benchmark overview
==============================================================================

* Benchmarking was done an Apple M2 Silicon.
* Test-cases were drawn from other packages and other examples seen in the wild


Validate JSON String
----------------------------------------------------------------------------


```{r}
json_str <- write_json_str(iris)

res00 <- bench::mark(
  jsonlite     = jsonlite::validate(json_str),
  jsonify      = jsonify::validate_json(json_str),
  yyjsonr      = yyjsonr::validate_json_str(json_str),
  check = TRUE
)
```

```{r echo=FALSE}
res00$benchmark <- 'Validate JSON String'
knitr::kable(res00[,1:5])
plot(res00) + theme_bw() + theme(legend.position = 'none')
```



To JSON String
----------------------------------------------------------------------------


```{r}
res01 <- bench::mark(
  jsonlite = jsonlite::toJSON(iris),
  jsonify  = jsonify::to_json(iris),
  yyjsonr  = yyjsonr::write_json_str(iris),
  check = FALSE
)
```


```{r echo=FALSE}
res01$benchmark <- 'To JSON String'
knitr::kable(res01[,1:5])
plot(res01) + theme_bw() + theme(legend.position = 'none')
```



From JSON String
----------------------------------------------------------------------------

```{r}
json_str <- write_json_str(iris)

res02 <- bench::mark(
  jsonlite     = jsonlite::fromJSON(json_str),
  jsonify      = jsonify::from_json(json_str),
  rcppsimdjson = RcppSimdJson::fparse(json_str),
  yyjsonr      = yyjsonr::read_json_str(json_str),
  check = TRUE
)
```

```{r echo=FALSE}
res02$benchmark <- 'From JSON String'
knitr::kable(res02[,1:5])
plot(res02) + theme_bw() + theme(legend.position = 'none')
```


From JSON raw vector
----------------------------------------------------------------------------

```{r warning=FALSE}
# a <- nanonext::ncurl("https://postman-echo.com/get", convert = FALSE)

# raw_data <- a$data
raw_data <- as.raw(c(0x7b, 0x0a, 0x20, 0x20, 0x22, 0x61, 0x72, 0x67, 0x73, 
0x22, 0x3a, 0x20, 0x7b, 0x7d, 0x2c, 0x0a, 0x20, 0x20, 0x22, 0x68, 
0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x22, 0x3a, 0x20, 0x7b, 0x0a, 
0x20, 0x20, 0x20, 0x20, 0x22, 0x78, 0x2d, 0x66, 0x6f, 0x72, 0x77, 
0x61, 0x72, 0x64, 0x65, 0x64, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 
0x22, 0x3a, 0x20, 0x22, 0x68, 0x74, 0x74, 0x70, 0x73, 0x22, 0x2c, 
0x0a, 0x20, 0x20, 0x20, 0x20, 0x22, 0x78, 0x2d, 0x66, 0x6f, 0x72, 
0x77, 0x61, 0x72, 0x64, 0x65, 0x64, 0x2d, 0x70, 0x6f, 0x72, 0x74, 
0x22, 0x3a, 0x20, 0x22, 0x34, 0x34, 0x33, 0x22, 0x2c, 0x0a, 0x20, 
0x20, 0x20, 0x20, 0x22, 0x68, 0x6f, 0x73, 0x74, 0x22, 0x3a, 0x20, 
0x22, 0x70, 0x6f, 0x73, 0x74, 0x6d, 0x61, 0x6e, 0x2d, 0x65, 0x63, 
0x68, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x22, 0x2c, 0x0a, 0x20, 0x20, 
0x20, 0x20, 0x22, 0x78, 0x2d, 0x61, 0x6d, 0x7a, 0x6e, 0x2d, 0x74, 
0x72, 0x61, 0x63, 0x65, 0x2d, 0x69, 0x64, 0x22, 0x3a, 0x20, 0x22, 
0x52, 0x6f, 0x6f, 0x74, 0x3d, 0x31, 0x2d, 0x36, 0x35, 0x33, 0x62, 
0x61, 0x33, 0x38, 0x65, 0x2d, 0x35, 0x65, 0x65, 0x66, 0x32, 0x39, 
0x64, 0x38, 0x30, 0x61, 0x35, 0x63, 0x65, 0x62, 0x32, 0x30, 0x33, 
0x65, 0x36, 0x64, 0x32, 0x64, 0x35, 0x61, 0x22, 0x0a, 0x20, 0x20, 
0x7d, 0x2c, 0x0a, 0x20, 0x20, 0x22, 0x75, 0x72, 0x6c, 0x22, 0x3a, 
0x20, 0x22, 0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x70, 
0x6f, 0x73, 0x74, 0x6d, 0x61, 0x6e, 0x2d, 0x65, 0x63, 0x68, 0x6f, 
0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65, 0x74, 0x22, 0x0a, 0x7d
))

res03 <- bench::mark(
  jsonlite     = jsonlite::fromJSON(rawConnection(raw_data)),
  rcppsimdjson = RcppSimdJson::fparse(raw_data),
  yyjsonr      = yyjsonr::read_json_raw(raw_data),
  check = FALSE
)
```


```{r echo=FALSE}
res03$benchmark <- 'From JSON Raw Vector'
knitr::kable(res03[,1:5])
plot(res03) + theme_bw() + theme(legend.position = 'none')
```




To JSON File
----------------------------------------------------------------------------

```{r}
json_file <- tempfile()

res04 <- bench::mark(
  jsonlite = jsonlite::write_json(iris, json_file),
  yyjsonr  = yyjsonr::write_json_file(iris, json_file),
  check = FALSE
)

```

```{r echo=FALSE}
res04$benchmark <- 'To JSON File'
knitr::kable(res04[, 1:5])
plot(res04) + theme_bw() + theme(legend.position = 'none')
```


From JSON File
------------------------------------------------------------------------------

```{r}
json_file <- tempfile()
jsonlite::write_json(iris, json_file)

res05 <- bench::mark(
  jsonlite     = jsonlite::fromJSON(file(json_file)), 
  rcppsimdjson = RcppSimdJson::fload(json_file), 
  yyjsonr      = yyjsonr::read_json_file(json_file),
  check = TRUE
)

```

```{r echo=FALSE}
res05$benchmark <- 'From JSON File'
knitr::kable(res05[, 1:5])
plot(res05) + theme_bw() + theme(legend.position = 'none')
```



From NDJSON file
-------------------------------------------------------------------------------


```{r include = FALSE}
ndjson_filename <- tempfile()
df <- head( nycflights13::flights, 1000)
jsonlite::stream_out(df, file(ndjson_filename), verbose = FALSE)

res06 <- bench::mark(
  ndjson   = ndjson::stream_in(ndjson_filename),
  jsonlite = jsonlite::stream_in(file(ndjson_filename), verbose = FALSE),
  jsonify  = jsonify::from_ndjson(ndjson_filename),
  yyjsonr  = yyjsonr::read_ndjson_file  (ndjson_filename),
  check = FALSE
)
```

```{r echo=FALSE}
res06$benchmark <- 'From NDJSON File'
knitr::kable(res06[, 1:5])
plot(res06) + theme_bw() + theme(legend.position = 'none')
```



To NDJSON File
-------------------------------------------------------------------------------


```{r include = FALSE}
ndjson_filename <- tempfile()
df <- head( nycflights13::flights, 1000)

res07 <- bench::mark(
  jsonlite = jsonlite::stream_out(df, file(ndjson_filename), verbose = FALSE),
  yyjsonr  = yyjsonr::write_ndjson_file(df, ndjson_filename),
  check = FALSE
)
```


```{r echo=FALSE}
res07$benchmark <- 'To NDJSON File'
knitr::kable(res07[, 1:5])
plot(res07) + theme_bw() + theme(legend.position = 'none')
```


To NDJSON String
-------------------------------------------------------------------------------


```{r message=FALSE, include = FALSE}
ndjson_filename <- tempfile()
df <- head( nycflights13::flights, 1000)

res08 <- bench::mark(
  jsonify  = jsonify::to_ndjson(df),
  jsonlite = jsonlite::stream_out(df, con = textConnection(NULL, "w"), name = "greg", local = TRUE),
  yyjsonr  = yyjsonr::write_ndjson_str(df),
  check = FALSE
)
```

```{r echo=FALSE}
res08$benchmark <- 'To NDJSON String'
knitr::kable(res08[, 1:5])
plot(res08) + theme_bw() + theme(legend.position = 'none')
```


From GeoJSON String
----------------------------------------------------------------------------

```{r}
res13 <- bench::mark(
  geojsonsf    = geojsonsf::geojson_sf(geojsonsf::geo_melbourne),
  yyjsonr      = yyjsonr::read_geojson_str(geojsonsf::geo_melbourne),
  check = FALSE
)

```

```{r echo=FALSE}
res13$benchmark <- 'from GeoJSON string'
knitr::kable(res13[,1:5])
plot(res13) + theme_bw() + theme(legend.position = 'none')
```


To GeoJSON String
----------------------------------------------------------------------------

```{r}
sf_obj <- sf::st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE)

res14 <- bench::mark(
  geojsonsf    = geojsonsf::sf_geojson(sf_obj),
  yyjsonr      = yyjsonr::write_geojson_str(sf_obj),
  check = FALSE
)

```

```{r echo=FALSE}
res14$benchmark <- 'to GeoJSON string'
knitr::kable(res14[,1:5])
plot(res14) + theme_bw() + theme(legend.position = 'none')
```





Benchmark from `{RcppSimdJson}`
----------------------------------------------------------------------------

```{r}
jsonfile <- system.file("jsonexamples", "twitter.json", package="RcppSimdJson")
json <- paste(readLines(jsonfile), collapse = "\n")

res09 <- bench::mark(
  jsonlite     = jsonlite::fromJSON(json),
  rcppsimdjson = RcppSimdJson::fparse(json),
  yyjsonr      = yyjsonr::read_json_str(json),
  check = FALSE
)
```

```{r echo=FALSE}
res09$benchmark <- 'Rcppsimdjson benchmark'
knitr::kable(res09[, 1:5])
plot(res09) + theme_bw() + theme(legend.position = 'none')
```

Benchmark 1 from `{jsonify}` 
----------------------------------------------------------------------------

```{r}
n <- 1e5
df <- data.frame(
  id = 1:n
  , value = sample(letters, size = n, replace = T)
  , val2 = rnorm(n = n)
  , log = sample(c(T,F), size = n, replace = T)
  , stringsAsFactors = FALSE
)

res10 <- bench::mark(
  jsonlite = jsonlite::toJSON( df ),
  jsonify  = jsonify::to_json( df ),
  yyjsonr  = yyjsonr::write_json_str( df ),
  check = FALSE
)
```

```{r echo=FALSE}
res10$benchmark <- 'jsonify benchmark (1)'
knitr::kable(res10[,1:5])
plot(res10) + theme_bw() + theme(legend.position = 'none')
```

Benchmark 2 from `{jsonify}` 
----------------------------------------------------------------------------

```{r}
n <- 1e4
x <- list(
  x = rnorm(n = n)
  , y = list(x = rnorm(n = n))
  , z = list( list( x = rnorm(n = n)))
  , xx = rnorm(n = n)
  , yy = data.frame(
      id = 1:n
      , value = sample(letters, size = n, replace = T)
      , val2 = rnorm(n = n)
      , log = sample(c(T,F), size = n, replace = T)
    )
)

res11 <- bench::mark(
 jsonlite = jsonlite::toJSON( x ),
 jsonify  = jsonify::to_json( x ),
 yyjsonr  = yyjsonr::write_json_str(x),
 check = FALSE
)
```

```{r echo=FALSE}
res11$benchmark <- 'jsonify benchmark (2)'
knitr::kable(res11[,1:5])
plot(res11) + theme_bw() + theme(legend.position = 'none')
```


Benchmark 3 from `{jsonify}` 
----------------------------------------------------------------------------

```{r}
jlt <- jsonlite::toJSON( x )

res12 <- bench::mark(
  jsonlite     = jsonlite::fromJSON( jlt ),
  jsonify      = jsonify::from_json( jlt ),
  rcppsimdjson = RcppSimdJson::fparse(jlt),
  yyjsonr      = yyjsonr::read_json_str(jlt),
  check = FALSE
)

```

```{r echo=FALSE}
res12$benchmark <- 'jsonify benchmark (3)'
knitr::kable(res12[,1:5])
plot(res12) + theme_bw() + theme(legend.position = 'none')
```


Summary
===============================================================================

```{r echo = FALSE, fig.width = 8, fig.height = 6}
library(dplyr)
plot_df <- bind_rows(
  res00, res01, res02, res03, res04, res05,
  res13, res14, # geojson
  res06, res07, res08, res09, res10, res11, res12,
)

plot_df$benchmark <- factor(
  plot_df$benchmark, 
  levels = unique(plot_df$benchmark)
)

plot_df <- plot_df %>% 
  mutate(
    package = as.character(expression),
    iters   = `itr/sec`,
    speed   = iters
  ) %>%
  select(benchmark, package, iters, speed)

plot_df <- plot_df %>%
  group_by(benchmark) %>%
  mutate(
    ref_speed = speed[which(package %in% c('jsonlite', 'geojsonsf'))],
    speed = speed / ref_speed
  ) %>%
  ungroup()

ggplot(plot_df) + 
  geom_col(aes(package, speed, fill = package), 
           position = position_dodge2(preserve = "single")) + 
  facet_wrap(~benchmark, scales = 'free_y', ncol = 3) + 
  theme_bw() + 
  theme(legend.position = 'none') + 
  scale_fill_manual(values = c(rep(grey(0.5), 5), 'dodgerblue3')) +
  geom_hline(yintercept = 1, color = 'red', alpha = 0.5, linetype = 2) + 
  labs(
    x = NULL,
    y = "Factor speed increase over reference implementation",
    title = "Speed-up compared to reference implementation",
    subtitle = "Red line indicates reference implementation {jsonlite} or {geojsonsf}"
  )

# ggsave("./man/figures/benchmark-summary.png", width = 12, height = 10)
# saveRDS(plot_df, "man/benchmark/cache-df-types.rds")
```



