---
title: "Configuration Options for Parsing from JSON"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Configuration Options for Parsing from JSON}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
suppressPackageStartupMessages({
  library(bit64)
  library(yyjsonr)
})
```


Mixture of numeric and string types
-----------------------------------------------------------------------------

```{r}
# a JSON array of mixed string and numeric types
json <- '[1,2,3,"apple"]'
```


```{r}
# jsonlite returns an atomic character vector (by default)
jsonlite::fromJSON(json)
```


```{r}
# yyjsonr can behave the same as jsonlite's default
yyjsonr::read_json_str(json, promote_num_to_string = TRUE)
```


```{r}
# Keep all types as-is and return as a list
yyjsonr::read_json_str(json, promote_num_to_string = FALSE)
```





Large integers
-----------------------------------------------------------------------------

```{r}
str <- '[1, 2, 274877906944]'

read_json_str(str, int64 = 'string')

read_json_str(str, int64 = 'bit64')
```


Missing list elements (when parsing data.frames)
-----------------------------------------------------------------------------

```{r}
str <- '[{"a":1, "b":[1,2]}, {"a":2}]'

read_json_str(str, missing_list_elem = 'null')

read_json_str(str, missing_list_elem = 'na')
```


Vectors to data.frame
-----------------------------------------------------------------------------

```{r}
str <- '{"a":[1,2],"b":["apple","banana"]}'

read_json_str(str, vectors_to_df = FALSE)

read_json_str(str, vectors_to_df =  TRUE)
```


String special values: 'NA'
-----------------------------------------------------------------------------

```{r}
str <- '["apple", "banana", null, "NA"]'

read_json_str(str, str_specials = 'string')

read_json_str(str, str_specials = 'special')
```


Numeric special values: 'NA', 'NaN', 'Inf', '-Inf'
-----------------------------------------------------------------------------

```{r}
str <- '[1.0, 2.0, null, "NA", "Inf", "-Inf", "NaN"]'

read_json_str(str, num_specials = 'string')

read_json_str(str, num_specials = 'special')
```


