---
title: "Configuration Options for Serializing to JSON"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Configuration Options for Serializing to JSON}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(yyjsonr)
```


data.frame as rows or columns
-----------------------------------------------------------------------------

```{r}
df <- data.frame(a = 1:2, b=c('apple', 'banana'))

cat(write_json_str(df, dataframe = 'rows'))

cat(write_json_str(df, dataframe = 'cols'))
```

factors as strings or integer
-----------------------------------------------------------------------------

```{r}
ff <- as.factor(c("apple", "apple", "banana"))

cat(write_json_str(ff, factor = 'string'))
cat(write_json_str(ff, factor = 'integer'))
```

Auto unbox scalar values
-----------------------------------------------------------------------------

```{r}
ll <- list(a = 1, b = "hello", c = 1:3)

cat(write_json_str(ll, auto_unbox = TRUE))

cat(write_json_str(ll, auto_unbox = FALSE))
```

Pretty
-----------------------------------------------------------------------------

```{r}
df <- data.frame(a = 1:2, b=c('apple', 'banana'))

cat(write_json_str(df, pretty = FALSE))

cat(write_json_str(df, pretty = TRUE))
```

Repair names of partially named lists
-----------------------------------------------------------------------------

```{r}
ll <- list(a = 1, "banana", c = "cat")

cat(write_json_str(ll, name_repair = 'none'))
cat(write_json_str(ll, name_repair = 'minimal'))
```

Numeric special values e.g. "NA"
-----------------------------------------------------------------------------

```{r}
vec <- c(1, 2, NA, NaN, Inf, -Inf)

cat(write_json_str(vec, num_specials = 'null'))

cat(write_json_str(vec, num_specials = 'string'))
```

String special values i.e. "NA"
-----------------------------------------------------------------------------

```{r}
vec <- c("apple", "banana", NA)

cat(write_json_str(vec, str_specials = 'null'))

cat(write_json_str(vec, str_specials = 'string'))
```


